"""Exporters: minimal DXF (LWPOLYLINE with bulges) and Gmsh .geo scripts."""
from __future__ import annotations

from .geometry import Geometry, arc_bulge


def _f(x: float) -> str:
    return f"{float(x):.12g}"


def to_dxf(geom: Geometry, layer: str = "0", spline_step_deg: float = 5.0) -> str:
    """Minimal DXF (R2000 flavour): one closed LWPOLYLINE per loop, arcs as bulges,
    spline edges as fine polylines."""
    lines = ["0", "SECTION", "2", "HEADER", "9", "$ACADVER", "1", "AC1015", "0", "ENDSEC",
             "0", "SECTION", "2", "ENTITIES"]
    handle = 0x100
    for lp in geom.loops:
        verts = []                                   # (x, y, bulge)
        for e in lp.evaluators():
            if e.kind == "arc":
                verts.append((e.p0[0], e.p0[1], arc_bulge(e.theta)))
            elif e.kind == "spline":
                verts += [(q[0], q[1], 0.0) for q in e.polyline(spline_step_deg)[:-1]]
            else:
                verts.append((e.p0[0], e.p0[1], 0.0))
        handle += 1
        lines += ["0", "LWPOLYLINE", "5", f"{handle:X}", "100", "AcDbEntity", "8", layer,
                  "100", "AcDbPolyline", "90", str(len(verts)), "70", "1"]
        for x, y, b in verts:
            lines += ["10", _f(x), "20", _f(y)]
            if b != 0.0:
                lines += ["42", _f(b)]
    for ch in geom.chains:                          # internal chains as open polylines
        verts = []
        for e in ch.evaluators():
            if e.kind == "arc":
                verts.append((e.p0[0], e.p0[1], arc_bulge(e.theta)))
            elif e.kind == "spline":
                verts += [(q[0], q[1], 0.0) for q in e.polyline(spline_step_deg)[:-1]]
            else:
                verts.append((e.p0[0], e.p0[1], 0.0))
        verts.append((ch.points[-1][0], ch.points[-1][1], 0.0))
        handle += 1
        lines += ["0", "LWPOLYLINE", "5", f"{handle:X}", "100", "AcDbEntity", "8", layer + "_cuts",
                  "100", "AcDbPolyline", "90", str(len(verts)), "70", "0"]
        for x, y, b in verts:
            lines += ["10", _f(x), "20", _f(y)]
            if b != 0.0:
                lines += ["42", _f(b)]
    lines += ["0", "ENDSEC", "0", "EOF"]
    return "\n".join(lines) + "\n"


def save_dxf(geom: Geometry, path: str, **kw) -> None:
    with open(path, "w") as f:
        f.write(to_dxf(geom, **kw))


def to_geo(geom: Geometry, lc: float = 1.0, recombine: bool = False, physical: bool = True) -> str:
    """Gmsh .geo script: Points, Lines, Circle arcs (start, centre, end), Splines through the
    interior points of spline edges, one Plane Surface per region (internal chains are shared by
    their two regions, or embedded in a region that lies on both sides).

    ``lc`` is the target mesh size (1.0 = one lattice unit = the smallest feature).
    With ``recombine`` the script asks Gmsh for an all-quad mesh (Frontal-Delaunay for quads + Blossom).
    """
    out = ["// generated by geo2d", "// Point comments give the interior angle of the domain at the vertex (180 = smooth joint)",
           f"lc = {_f(lc)};"]
    pid = cid = 0
    tag_curves: dict[str, list[int]] = {}
    point_id: dict = {}

    def point(p, comment=""):
        nonlocal pid
        key = (round(float(p[0]), 9), round(float(p[1]), 9))
        if key not in point_id:
            pid += 1
            point_id[key] = pid
            out.append(f"Point({pid}) = {{{_f(p[0])}, {_f(p[1])}, 0, lc}};{comment}")
        return point_id[key]

    curve_of: dict = {}                      # ("loop"|"chain", idx, ei) -> curve id (oriented as stored)

    def curve(src, kind, idx, ei, e, a, b):
        nonlocal cid, pid
        cid += 1
        if e.kind == "line":
            out.append(f"Line({cid}) = {{{a}, {b}}};")
        elif e.kind == "arc":
            pid += 1
            out.append(f"Point({pid}) = {{{_f(e.center[0])}, {_f(e.center[1])}, 0, lc}};")
            out.append(f"Circle({cid}) = {{{a}, {pid}, {b}}};")
        else:
            inner = []
            for q in src.interior[ei]:
                pid += 1
                out.append(f"Point({pid}) = {{{_f(q[0])}, {_f(q[1])}, 0, lc}};")
                inner.append(pid)
            out.append(f"Spline({cid}) = {{{', '.join(map(str, [a] + inner + [b]))}}};")
        curve_of[(kind, idx, ei)] = cid
        tag = src.tags[ei] if src.tags is not None else ("outer" if kind == "loop" and idx == 0 else "hole" if kind == "loop" else "cut")
        tag_curves.setdefault(str(tag), []).append(cid)

    for li, lp in enumerate(geom.loops):
        out.append(f"// loop {li}: {'outer boundary' if li == 0 else 'hole'}")
        ids = [point(p, f"  // angle {_f(round(float(ang), 6))}") for p, ang in zip(lp.points, lp.interior_angles())]
        for i, e in enumerate(lp.evaluators()):
            curve(lp, "loop", li, i, e, ids[i], ids[(i + 1) % lp.n])
    for ci, ch in enumerate(geom.chains):
        out.append(f"// chain {ci}: internal boundary between regions {ch.regions[0]} and {ch.regions[1]}")
        ids = [point(p) for p in ch.points]
        for i, e in enumerate(ch.evaluators()):
            curve(ch, "chain", ci, i, e, ids[i], ids[i + 1])
    lid = 0
    if not geom.chains:
        loop_ids = []
        for li, lp in enumerate(geom.loops):
            lid += 1
            out.append(f"Curve Loop({lid}) = {{{', '.join(str(curve_of[('loop', li, i)]) for i in range(lp.n))}}};")
            loop_ids.append(lid)
        out.append(f"Plane Surface(1) = {{{', '.join(map(str, loop_ids))}}};")
        surfaces = {0: 1}
    else:
        from .regions import _faces, _tol
        G, faces, _ = _faces(geom, _tol(geom, None))
        surfaces = {}
        for r, f in enumerate(faces):
            loop_ids, embedded = [], []
            for cyc in [f["outer"]] + f["holes"]:
                signed = []
                for h in cyc["hes"]:
                    ed = G.edges[h // 2]
                    c = curve_of[(ed["kind"], ed["idx"], ed["ei"])]
                    signed.append(c if h % 2 == 0 else -c)
                dup = {abs(c) for c in signed if -c in signed}
                embedded += sorted(dup)
                signed = [c for c in signed if abs(c) not in dup]
                if signed:
                    lid += 1
                    out.append(f"Curve Loop({lid}) = {{{', '.join(map(str, signed))}}};")
                    loop_ids.append(lid)
            sid = r + 1
            out.append(f"Plane Surface({sid}) = {{{', '.join(map(str, loop_ids))}}};")
            if embedded:
                out.append(f"Curve{{{', '.join(map(str, embedded))}}} In Surface{{{sid}}};")
            surfaces[r] = sid
    if physical:
        for tag, ids in tag_curves.items():
            out.append(f'Physical Curve("{tag}") = {{{", ".join(map(str, ids))}}};')
        for r, sid in surfaces.items():
            out.append(f'Physical Surface("region_{r}", {sid}) = {{{sid}}};')
    if recombine:
        out += ["Mesh.Algorithm = 8;", "Mesh.RecombinationAlgorithm = 1;", "Mesh.RecombineAll = 1;"]
    return "\n".join(out) + "\n"


def save_geo(geom: Geometry, path: str, **kw) -> None:
    with open(path, "w") as f:
        f.write(to_geo(geom, **kw))
